import type { Metadata } from "next";
import Script from "next/script";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Dreamlity - AI Generated Bedtime Stories",
  description: "Generated by Dreamlity",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Analytics script (Paynext) - deferred to after interactive load */}
        <Script
          src="https://analytics.paynext.app/script.js"
          strategy="afterInteractive"
          data-website-id="72caaa5b-2adb-470b-a106-b17e9028aebb"
        />

        {children}

      </body>
      
    </html>
  );
}
